online_bookshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from profiles import views
from shop import views as shop_views

urlpatterns = [
    path("", shop_views.home, name='home'),
    path("admin/", admin.site.urls),
    path("profiles/", include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'profiles'
urlpatterns = [
    path('register/', views.RegistrationFormView, name='register'),
    path('profile/', views.ProfileView, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='profiles/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='profiles/logout.html'), name='logout'),
    path('update-profile/', views.ProfileEdit, name='update-profile'),
    path('password-change/', views.PasswordsChangeView.as_view(),
         name='password-change'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),
    path('process_review/', views.processReview, name='process_review'),
    path('product/<int:book_id>',
         views.productDetail, name='product-detail'),
    path('recommendation/', views.returnRecommendation, name="recommendation"),
    path('search', views.searchProduct, name="search"),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

from shop.models import Product


# Create your models here.

# Profile Table for user for facilitating extended features

# It has one to one relationship with user table


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True)
    profile_pic = models.ImageField(default='default.png', upload_to='profile')

    def __str__(self):
        return f'{self.user.username} Profile'


# model for cart
class Order(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False, null=True)
    transaction_id = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f'{self.profile} Order no {self.id}'

    @ property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @ property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True

            return shipping


# Item detail of Cart
class OrderItem(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @ property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

    def __str__(self):
        return str(self.product.product_name)


# Delivery Address
class ShippingAddress(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=200, blank=True)
    zipcode = models.CharField(max_length=200, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.address)

# For recommendation analysis


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=100, default='Untitled')
    rating = models.CharField(max_length=70)
    review = models.CharField(max_length=250)
    rated_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} profile {self.product.product_name} rating'

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from .models import Profile


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Username'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Email'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Type Password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        # for disabling long default help text


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileUpdate(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_pic']


class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(
        label='Password Confirmation', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

profiles/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse, reverse_lazy
from .forms import UserRegistrationForm, UserUpdateForm, ProfileUpdate, ChangePasswordForm
from django.contrib import messages
from shop.models import Product
from .models import Rating, Order, Product, OrderItem, ShippingAddress
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from math import sqrt, ceil
import json
import datetime


def RegistrationFormView(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')
            return redirect('/')

    else:
        form = UserRegistrationForm()

    order = {'get_cart_total': 0, 'get_cart_items': 0}
    cartItems = order['get_cart_items']
    return render(request, 'profiles/register.html', {'form': form, 'cartItems': cartItems})


# searching product
def searchProduct(request):
    if request.user.is_authenticated:
        customer = request.user.profile
        # tuple unpacking
        order, created = Order.objects.get_or_create(
            profile=customer, completed=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartItems = order['get_cart_items']
    if request.method == 'POST':
        search = request.POST.get('search')
        if search:
            product = Product.objects.filter(product_name__icontains=search)
            data = {'product': product, 'cartItems': cartItems}
            return render(request, 'profiles/search.html', data)
        else:
            data = {'product': None, 'cartItems': cartItems}
            return render(request, 'profiles/search.html', data)

# data for single product/book


def productDetail(request, book_id):
    if request.user.is_authenticated:
        customer = request.user.profile
        # tuple unpacking
        order, created = Order.objects.get_or_create(
            profile=customer, completed=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0, 'shipping': False}
        cartItems = order['get_cart_items']

    book = Product.objects.get(id=book_id)
    ratings = Rating.objects.filter(product=book)
    data = {'book': book, 'ratings': ratings,
            'order': order, 'cartItems': cartItems}
    print(ratings)
    return render(request, 'profiles/product.html', data)


# for updating Cart
def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action: ', action)
    print('ProductId:', productId)

    customer = request.user.profile
    product = Product.objects.get(id=productId)

    # tuple unpacking
    order, created = Order.objects.get_or_create(
        profile=customer, completed=False)
    orderItem, created = OrderItem.objects.get_or_create(
        order=order, product=product)

    if action == 'add' and orderItem.quantity < product.quantity:
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse("Item was added", safe=False)


# Editing User profile
@login_required
def ProfileEdit(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdate(request.POST, request.FILES,
                               instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('profiles:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdate(instance=request.user.profile)

    if request.user.is_authenticated:
        customer = request.user.profile
        # tuple unpacking
        order, created = Order.objects.get_or_create(
            profile=customer, completed=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartItems = order['get_cart_items']
    return render(request, 'profiles/edit_profile.html', {'cartItems': cartItems, 'u_form': u_form, 'p_form': p_form})


@login_required
def ProfileView(request):
    if request.user.is_authenticated:
        customer = request.user.profile
        # tuple unpacking
        order, created = Order.objects.get_or_create(
            profile=customer, completed=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartItems = order['get_cart_items']
    return render(request, 'profiles/profile.html', {'cartItems': cartItems})


# Password Change
class PasswordsChangeView(PasswordChangeView):
    success_url = reverse_lazy('home')
    form_class = ChangePasswordForm
    template_name = 'profiles/change_password.html'


# Data for Carts


def cart(request):
    if request.user.is_authenticated:
        customer = request.user.profile
        # tuple unpacking
        order, created = Order.objects.get_or_create(
            profile=customer, completed=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartItems = order['get_cart_items']

    data = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'profiles/cart.html', data)

# Data for checkout


def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.profile
        # tuple unpacking
        order, created = Order.objects.get_or_create(
            profile=customer, completed=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0, 'shipping': False}
        cartItems = order['get_cart_items']

    data = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'profiles/checkout.html', data)


def recommendationGenerator(request):
    
    books = Product.objects.all()
    ratings = Rating.objects.all()
    
    x = []
    y = []
    A = []
    B = []
    C = []
    D = []
    
    for item in books:
        x = [item.id, item.product_name, item.product_pic.url,
             item.genres, item.digital, item.quantity, item.price]
        y += [x]
    books_df = pd.DataFrame(
        y, columns=['bookId', 'product_name', 'product_pic', 'genres', 'digital', 'quantity', 'price'])
    print("Books data frame")
    print(books_df)
    print(books_df.dtypes)

    
    for item in ratings:
        A = [item.user.id, item.product.id, item.rating]
        B += [A]
    rating_df = pd.DataFrame(B, columns=['userId', 'bookId', 'rating'])
    print("Rating Dataframe")
    rating_df['userId'] = rating_df['userId'].astype(str).astype(np.int64)
    rating_df['bookId'] = rating_df['bookId'].astype(str).astype(np.int64)
    rating_df['rating'] = rating_df['rating'].astype(str).astype(np.float)
    print(rating_df)
    print(rating_df.dtypes)
    if request.user.is_authenticated:
        userid = request.user.id
        
        userInput = Rating.objects.select_related(
            'product').filter(user=userid)
        print(userInput)
        if userInput.count() == 0:
            recommenderQuery = None
            userInput = None
        else:
            for item in userInput:
                C = [item.product.product_name, item.rating]
                D += [C]
            inputBooks = pd.DataFrame(D, columns=['product_name', 'rating'])
            print("Rated books")
            inputBooks['rating'] = inputBooks['rating'].astype(
                str).astype(np.float)
            print(inputBooks.dtypes)

            
            inputId = books_df[books_df['product_name'].isin(
                inputBooks['product_name'].tolist())]
            

            inputBooks = pd.merge(inputId, inputBooks)
            
            print(inputBooks)

           
            userSubset = rating_df[rating_df['bookId'].isin(
                inputBooks['bookId'].tolist())]
            print(userSubset.head())

            
            userSubsetGroup = userSubset.groupby(['userId'])

            
            userSubsetGroup = sorted(
                userSubsetGroup,  key=lambda x: len(x[1]), reverse=True)

            print(userSubsetGroup[0:])

            userSubsetGroup = userSubsetGroup[0:]

            
            pearsonCorrelationDict = {}

        
            for name, group in userSubsetGroup:
                
                group = group.sort_values(by='bookId')
                inputBooks = inputBooks.sort_values(by='bookId')
                
                nRatings = len(group)
                
                temp_df = inputBooks[inputBooks['bookId'].isin(
                    group['bookId'].tolist())]
                
                tempRatingList = temp_df['rating'].tolist()
                
                tempGroupList = group['rating'].tolist()
                
                Sxx = sum([i**2 for i in tempRatingList]) - \
                    pow(sum(tempRatingList), 2)/float(nRatings)
                Syy = sum([i**2 for i in tempGroupList]) - \

profiles/templates/profiles/base.html
{% load static %}
{% load profiles_extras %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Online Bookshop</title>
        <link rel="stylesheet"
              type="text/css"
              href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/brands.css' %}">
        <link rel="stylesheet" href="{% static 'css/solid.css' %}">
        <link rel="stylesheet" href="{% static 'css/regular.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <script type="text/javascript">
          var user = "{{request.user}}";

            function getCookie(name) {
              let cookieValue = null;
              if (document.cookie && document.cookie !== '') {
                  const cookies = document.cookie.split(';');
                  for (let i = 0; i < cookies.length; i++) {
                      const cookie = cookies[i].trim();
                      // Does this cookie string begin with the name we want?
                      if (cookie.substring(0, name.length + 1) === (name + '=')) {
                          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                          break;
                      }
                  }
              }
              return cookieValue;
          }
          const csrftoken = getCookie('csrftoken');
        </script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark sticky-top">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link user-name"
                               data-user="{{ request.user }}"
                               style="display: inline-block;"
                               href="{% url 'profiles:profile' %}">
                                <img class="rounded-circle"
                                     style="width:25px;
                                            margin-right: 2px;"
                                     src="{{ user.profile.profile_pic.url }}">
                                {{ user.username }}
                            </a>
                        </li>
                        {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'admin:index' %}">Admin Panel</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profiles:recommendation' %}">Recommendation</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profiles:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profiles:register' %}">Create Account</a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <div class="form-inline my-2 my-lg-0">
                            <a href="{% url 'profiles:cart' %}">
                                <img id="cart-icon" src="{% static 'images/cart.png' %}">
                                <p id="cart-total">{{ cartItems }}</p>
                            </a>
                        </div>
                        <li>
                            <a class="nav-item nav-link" href="{% url 'profiles:logout' %}">Logout</a>
                        </li>
                    {% endif %}
                    <form class="form-inline"
                          method="post"
                          action="{% url 'profiles:search' %}">
                        {% csrf_token %}
                        <input class="form-control mr-sm-2"
                               type="text"
                               name="search"
                               placeholder="Search">
                        <button class="btn btn-success" type="submit">Search</button>
                    </form>
                </ul>
            </div>
        </nav>
        {% block content %}{% endblock %}
        <br>
        <br>
        <br>
        <!-- Remove the container if you want to extend the Footer to full width. -->
        <div class="container-fluid my-5 col-lg">
            <footer class="bg-dark text-center text-lg-start text-white">
                <!-- Grid container -->
                <div class="container p-4">
                    <!--Grid row-->
                    <div class="row mt-4">
                        <!--Grid column-->
                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                            <h5 class="text-uppercase">See other books</h5>
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#!" class="text-white"><i class="fas fa-book fa-fw fa-sm me-2"></i>Bestsellers</a>
                                </li>
                                <li>
                                    <a href="#!" class="text-white"><i class="fas fa-book fa-fw fa-sm me-2"></i>All books</a>
                                </li>
                                <li>
                                    <a href="#!" class="text-white"><i class="fas fa-user-edit fa-fw fa-sm me-2"></i>Our authors</a>
                                </li>
                            </ul>
                        </div>
                        <!--Grid column-->
                        <!--Grid column-->
                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                            <h5 class="text-uppercase">Execution of the contract</h5>
                            <ul class="list-unstyled">
                                <li>
                                    <a href="#!" class="text-white"><i class="fas fa-shipping-fast fa-fw fa-sm me-2"></i>Supply</a>
                                </li>
                                <li>
                                    <a href="#!" class="text-white"><i class="fas fa-backspace fa-fw fa-sm me-2"></i>Returns</a>
                                </li>
                                <li>
                                    <a href="#!" class="text-white"><i class="far fa-file-alt fa-fw fa-sm me-2"></i>Regulations</a>
                                </li>
                                <li>
                                    <a href="#!" class="text-white"><i class="far fa-file-alt fa-fw fa-sm me-2"></i>Privacy policy</a>
                                </li>
                            </ul>
                        </div>
                        <!--Grid column-->
                        <!--Grid column-->
                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                            <h5 class="text-uppercase">Publishing house</h5>
                            <ul class="list-unstyled">
                                <li>
                                    <a href="#!" class="text-white">The BookStore</a>
                                </li>
                                <li>
                                    <a href="#!" class="text-white"><i class="fas fa-briefcase fa-fw fa-sm me-2"></i>Send us a book</a>
                                </li>
                            </ul>
                        </div>
                        <!--Grid column-->
                        <!--Grid column-->
                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                            <h5 class="text-uppercase">Write to us</h5>
                            <ul class="list-unstyled">
                                <li>
                                    <a href="#!" class="text-white"><i class="fas fa-at fa-fw fa-sm me-2"></i>Help in purchasing</a>
                                </li>
                                <li>
                                    <a href="#!" class="text-white"><i class="fas fa-shipping-fast fa-fw fa-sm me-2"></i>Check the order status</a>
                                </li>
                                <li>
                                    <a href="#!" class="text-white"><i class="fas fa-envelope fa-fw fa-sm me-2"></i>Join the newsletter</a>
                                </li>
                            </ul>
                        </div>
                        <!--Grid column-->
                    </div>
                    <!--Grid row-->
                </div>
                <!-- Grid container -->
                <!-- Copyright -->
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
                    © 2021 Copyright:
                    <a class="text-white" href="{% url 'home' %}">Mawlana Bhasani Science and Technology Univery</a>
                </div>
                <!-- Copyright -->
            </footer>
        </div>
        <!-- End of .container -->
        <!--JavaScript Files-->
        <script type="text/javascript" src="{% static 'js/popperJS.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/JQuery.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/updateCart.js' %}"></script>
        </script>
    </body>
</html>

profiles/templates/profiles/change_password.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row d-flex">
        <div class="container  col-md-6">
            <div class="box-element">
                <form method="post" enctype="multipart/form-data">
                    <fieldset class="form-group justify-content-center">
                        <legend class="border-bottom mb-4 text-center">
                            {{ user.username }} Password Change
                        </legend>
                        {% csrf_token %}
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group text-center">
                        <button class="btn btn-outline-info btn-block" type="submit">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

profiles/templates/profiles/login.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section container col-md-4 box-element mt-5">
        <form method="post" class="mt-2">
            {% csrf_token %}
            <fieldset class="form-group justify-content-center">
                <legend class="border-bottom mb-4 text-center"
                        style="background-color:#087889;">
                    USER LOGIN
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info btn-block" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small>
                Need An Account? <a class="ml-2" href="{% url 'profiles:register' %}">Sign Up Now</a>
            </small>
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    </div>
{% endblock content %}

profiles/templates/profiles/logout.html
{% extends "profiles/base.html" %}
{% block content %}
    <div class="container box-element">
        <h2>You have been logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'profiles:login' %}">Log In Again</a>
            </small>
        </div>
    </div>
{% endblock content %}

profiles/templates/profiles/profile.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-7">
                <div class="card p-3 py-4">
                    <div class="text-center">
                        <img class="rounded-circle"
                             width="200px;"
                             src="{{ user.profile.profile_pic.url }}">
                    </div>
                    <div class="text-center mt-3">
                        <h2 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h2>
                        <h2 class="account-heading">{{ user.username }}</h2>
                        <p class="text-secondary">{{ user.email }}</p>
                    </div>
                    <div class="d-flex justify-content-center flex-nowrap">
                        <a class="btn btn-secondary mt-4 mb-4"
                           href="{% url 'profiles:update-profile' %}">Edit Profile</a>
                        <a class="btn btn-secondary mt-4 mb-4"
                           href="{% url 'profiles:password-change' %}">Change Password</a>
                    </div>
                    <div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                            Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                            ex ea commodo consequat.
                            Duis aute irure dolor in reprehenderit in voluptate velit esse
                            cillum dolore eu fugiat nulla pariatur.
                        </p>
                    </div>
                    <div class="text-center mb-4">
                        <i class="fa-brands fa-facebook"></i>
                        <i class="fa-brands fa-twitter"></i>
                        <i class="fa-brands fa-github"></i>
                        <i class="fa-brands fa-linkedin"></i>
                    </div>
                    <div>
                        <p>Joined in {{ user.date_joined }}</p>
                        <p>Last logged in: {{ user.last_login }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}